
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  mr: {
    app_name: "AI कृषी मित्र",
    menu_dashboard: "डॅशबोर्ड",
    menu_market: "बाजार भाव",
    menu_weather: "हवामान",
    menu_crop_doctor: "पीक डॉक्टर",
    menu_knowledge: "कृषी ज्ञान",
    menu_schemes: "योजना",
    menu_voice: "व्हॉइस असिस्टंट",
    menu_soil: "माती परीक्षण",
    menu_yield: "उत्पन्न अंदाज",
    menu_area: "क्षेत्र मोजणी",
    
    live_system: "लाईव्ह सिस्टम",
    welcome_title: "नमस्कार,",
    welcome_subtitle: "तुमच्या शेतीचा आजचा अहवाल",
    weather_alert_title: "हवामान इशारा",
    weather_alert_msg: "पुढील २ तासात जोरदार पावसाची शक्यता आहे. काढणी केलेला माल सुरक्षित ठेवा.",
    
    quick_action_doctor: "पीक डॉक्टर",
    quick_action_doctor_desc: "झटपट रोग निदान",
    quick_action_market: "बाजार भाव",
    quick_action_market_desc: "ताजी अपडेट",
    quick_action_soil: "माती परीक्षण",
    quick_action_tools: "स्मार्ट टूल्स",

    govt_schemes: "शासकीय योजना",
    latest_news: "कृषी बातम्या",
    view_all: "सर्व पहा",
    
    schemes_title: "शासकीय योजना",
    schemes_desc: "शेतकऱ्यांसाठी विविध सरकारी योजनांची माहिती",
    scheme_benefit: "फायदा",
    scheme_deadline: "मुदत",
    apply_btn: "अर्ज करा",
    open_status: "सुरू आहे",
    closed_status: "बंद",

    market_title: "बाजार भाव",
    market_subtitle: "तुमच्या जवळील बाजार समित्यांचे भाव",
    price_label: "भाव",
    arrival_label: "आवक",

    weather_title: "हवामान अंदाज",
    weather_subtitle: "पुढील ३ दिवसांचा अंदाज",
    wind: "वारा",
    humidity: "आद्रता",
    uv_index: "उन",

    scan_title: "पीक डॉक्टर",
    scan_desc: "पिकाच्या पानाचा फोटो काढा आणि रोगाचे अचूक निदान मिळवा",
    take_photo: "फोटो काढा",
    upload_text: "किंवा फोटो अपलोड करा",
    analyzing: "तपासणी करत आहे...",
    analysis_report: "तपासणी अहवाल",
    save_report: "अहवाल जतन करा",
    share_expert: "तज्ञांना पाठवा",

    voice_title: "मी ऐकतोय...",
    voice_tap: "बोलण्यासाठी टॅप करा",
    voice_desc: "हवामान, पीक किंवा बाजारभावाबद्दल तुमच्या भाषेत विचारा.",
    voice_hints: [
      "सोयाबीनचा आजचा भाव काय आहे?",
      "आज पाऊस पडेल का?",
      "पीएम किसान योजनेची माहिती द्या",
      "कापसावर कोणती फवारणी करावी?"
    ],

    blog_title: "कृषी ज्ञान भांडार",
    blog_subtitle: "नवीन तंत्रज्ञान आणि यशोगाथा",
    read_article: "लेख वाचा",
    
    soil_title: "माती आरोग्य कार्ड",
    soil_subtitle: "NPK टाकून खताचा सल्ला मिळवा",
    n_label: "नायट्रोजन (N)",
    p_label: "फॉस्फरस (P)",
    k_label: "पोटॅशियम (K)",
    crop_input: "कोणते पीक घेणार आहात?",
    analyze_soil_btn: "खत व्यवस्थापन सल्ला मिळवा",
    soil_result_title: "AI मृदा सल्ला",

    yield_title: "उत्पन्न अंदाज",
    yield_subtitle: "AI वापरून उत्पन्नाचा अंदाज घ्या",
    sowing_date: "पेरणी तारीख",
    soil_type: "जमिनीचा प्रकार",
    irrigation_type: "सिंचन पद्धत",
    area_size: "क्षेत्र (एकर)",
    predict_btn: "उत्पन्न अंदाज सांगा",
    yield_result: "अपेक्षित उत्पन्न",

    area_title: "क्षेत्र मोजणी (सॅटेलाईट)",
    area_subtitle: "नकाशावर टॅप करून जमीन मोजा",
    total_area: "एकूण क्षेत्र",
    unit_sqm: "चौ. मीटर",
    unit_acre: "एकर",
    unit_guntha: "गुंठा",
    unit_hectare: "हेक्टर",
    unit_bigha: "बिघा",
    reset_map: "पुन्हा मोजा",
    undo_point: "मागे घ्या",

    author: "लेखक",
    date_format: "दिनांक",
  },
  hi: {
    app_name: "AI कृषि मित्र",
    menu_dashboard: "डैशबोर्ड",
    menu_market: "मंडी भाव",
    menu_weather: "मौसम",
    menu_crop_doctor: "फसल डॉक्टर",
    menu_knowledge: "कृषि ज्ञान",
    menu_schemes: "योजनाएं",
    menu_voice: "वॉयस असिस्टेंट",
    menu_soil: "मृदा परीक्षण",
    menu_yield: "उपज अनुमान",
    menu_area: "क्षेत्र मापन",

    live_system: "लाइव सिस्टम",
    welcome_title: "नमस्ते,",
    welcome_subtitle: "आपकी खेती की आज की रिपोर्ट",
    weather_alert_title: "मौसम चेतावनी",
    weather_alert_msg: "अगले 2 घंटों में भारी बारिश की संभावना है। फसल सुरक्षित करें।",

    quick_action_doctor: "फसल डॉक्टर",
    quick_action_doctor_desc: "त्वरित निदान",
    quick_action_market: "मंडी भाव",
    quick_action_market_desc: "ताज़ा अपडेट",
    quick_action_soil: "मृदा परीक्षण",
    quick_action_tools: "स्मार्ट टूल्स",

    govt_schemes: "सरकारी योजनाएं",
    latest_news: "कृषि समाचार",
    view_all: "सभी देखें",

    schemes_title: "सरकारी योजनाएं",
    schemes_desc: "किसानों के लिए विभिन्न सरकारी योजनाओं की जानकारी",
    scheme_benefit: "लाभ",
    scheme_deadline: "समय सीमा",
    apply_btn: "आवेदन करें",
    open_status: "खुला है",
    closed_status: "बंद",

    market_title: "मंडी भाव",
    market_subtitle: "आपके नजदीकी मंडी के भाव",
    price_label: "भाव",
    arrival_label: "आवक",

    weather_title: "मौसम पूर्वानुमान",
    weather_subtitle: "अगले 3 दिनों का अनुमान",
    wind: "हवा",
    humidity: "नमी",
    uv_index: "धूप",

    scan_title: "फसल डॉक्टर",
    scan_desc: "फसल की पत्ती की फोटो लें और बीमारी का सटीक निदान पाएं",
    take_photo: "फोटो लें",
    upload_text: "या फोटो अपलोड करें",
    analyzing: "जांच कर रहा है...",
    analysis_report: "जांच रिपोर्ट",
    save_report: "रिपोर्ट सेव करें",
    share_expert: "विशेषज्ञ को भेजें",

    voice_title: "मैं सुन रहा हूँ...",
    voice_tap: "बोलने के लिए टैप करें",
    voice_desc: "मौसम, फसल या बाजार भाव के बारे में अपनी भाषा में पूछें।",
    voice_hints: [
      "सोयाबीन का आज का भाव क्या है?",
      "क्या आज बारिश होगी?",
      "पीएम किसान योजना की जानकारी दें",
      "कपास पर कौन सा छिड़काव करें?"
    ],

    blog_title: "कृषि ज्ञान केंद्र",
    blog_subtitle: "नई तकनीक और सफलता की कहानियाँ",
    read_article: "लेख पढ़ें",
    
    soil_title: "मृदा स्वास्थ्य कार्ड",
    soil_subtitle: "NPK डालकर खाद की सलाह प्राप्त करें",
    n_label: "नाइट्रोजन (N)",
    p_label: "फास्फोरस (P)",
    k_label: "पोटेशियम (K)",
    crop_input: "कौन सी फसल उगा रहे हैं?",
    analyze_soil_btn: "खाद प्रबंधन सलाह प्राप्त करें",
    soil_result_title: "AI मृदा सलाह",

    yield_title: "उपज अनुमान",
    yield_subtitle: "AI का उपयोग करके उपज का अनुमान लगाएं",
    sowing_date: "बुवाई की तारीख",
    soil_type: "मिट्टी का प्रकार",
    irrigation_type: "सिंचाई का प्रकार",
    area_size: "क्षेत्र (एकड़)",
    predict_btn: "उपज अनुमान प्राप्त करें",
    yield_result: "अनुमानित उपज",

    area_title: "क्षेत्र मापन (सैटेलाइट)",
    area_subtitle: "मानचित्र पर टैप करके भूमि मापें",
    total_area: "कुल क्षेत्र",
    unit_sqm: "वर्ग मीटर",
    unit_acre: "एकड़",
    unit_guntha: "गुंठा",
    unit_hectare: "हेक्टेयर",
    unit_bigha: "बीघा",
    reset_map: "रीसेट करें",
    undo_point: "पीछे जाएं",

    author: "लेखक",
    date_format: "दिनांक",
  },
  en: {
    app_name: "AI Krushi Mitra",
    menu_dashboard: "Dashboard",
    menu_market: "Market",
    menu_weather: "Weather",
    menu_crop_doctor: "Crop Doctor",
    menu_knowledge: "Knowledge",
    menu_schemes: "Schemes",
    menu_voice: "Voice Assistant",
    menu_soil: "Soil Health",
    menu_yield: "Yield Predictor",
    menu_area: "Area Calc",

    live_system: "Live System",
    welcome_title: "Hello,",
    welcome_subtitle: "Here's your smart farming summary",
    weather_alert_title: "Weather Alert",
    weather_alert_msg: "Heavy rain expected in next 2 hours. Secure harvested crops.",

    quick_action_doctor: "Crop Doctor",
    quick_action_doctor_desc: "Instant Diagnosis",
    quick_action_market: "Market Rates",
    quick_action_market_desc: "Live Updates",
    quick_action_soil: "Soil Health",
    quick_action_tools: "Smart Tools",

    govt_schemes: "Govt Schemes",
    latest_news: "Agri News",
    view_all: "View All",

    schemes_title: "Government Schemes",
    schemes_desc: "Benefits and subsidies for farmers",
    scheme_benefit: "Benefit",
    scheme_deadline: "Deadline",
    apply_btn: "Apply Now",
    open_status: "Open",
    closed_status: "Closed",

    market_title: "Market Rates",
    market_subtitle: "Live prices from local Mandis",
    price_label: "Price",
    arrival_label: "Arrival",

    weather_title: "Weather Forecast",
    weather_subtitle: "Forecast for next 3 days",
    wind: "Wind",
    humidity: "Humidity",
    uv_index: "UV Index",

    scan_title: "Crop Doctor",
    scan_desc: "Upload a photo of your crop leaf for instant diagnosis",
    take_photo: "Take Photo",
    upload_text: "or drag and drop here",
    analyzing: "Analyzing...",
    analysis_report: "Analysis Report",
    save_report: "Save Report",
    share_expert: "Share with Expert",

    voice_title: "I'm listening...",
    voice_tap: "Tap to Speak",
    voice_desc: "Ask about weather, crops, or market rates in your language.",
    voice_hints: [
      "What is the soyabean rate?",
      "Will it rain today?",
      "Explain PM Kisan Scheme",
      "Identify crop disease"
    ],

    blog_title: "Knowledge Hub",
    blog_subtitle: "Latest farming techniques",
    read_article: "Read Article",
    
    soil_title: "Soil Health Card",
    soil_subtitle: "Enter NPK for fertilizer advice",
    n_label: "Nitrogen (N)",
    p_label: "Phosphorus (P)",
    k_label: "Potassium (K)",
    crop_input: "Which crop are you growing?",
    analyze_soil_btn: "Get Fertilizer Advice",
    soil_result_title: "AI Soil Advice",

    yield_title: "Yield Predictor",
    yield_subtitle: "Estimate production using AI",
    sowing_date: "Sowing Date",
    soil_type: "Soil Type",
    irrigation_type: "Irrigation",
    area_size: "Area (Acres)",
    predict_btn: "Predict Yield",
    yield_result: "Expected Yield",

    area_title: "Area Calculator (Sat)",
    area_subtitle: "Tap on map to calculate field area",
    total_area: "Total Area",
    unit_sqm: "Sq. Meter",
    unit_acre: "Acre",
    unit_guntha: "Guntha",
    unit_hectare: "Hectare",
    unit_bigha: "Bigha",
    reset_map: "Reset",
    undo_point: "Undo",

    author: "Author",
    date_format: "Date",
  }
};
